language: node_js
node_js:
- '0.10'
notifications:
  email: false
branches:
  only:
    - master
env:
  global:
  - secure: SfSHCMmLFvFf2ImHNqNt2xv7rgPD9MXYR2sy+uPOrzq1z4zceK5BRf7SaoZR+vmj7plaKdTnVfkdCw0UhAOdVEnfTZENfBaXsVHwdE0HiWVvTt6avQ+EMia0U+HLd5FpgoejMI9/eq5IkWav6/Q4wK1K77F1nCl3TfjZYB36pf0=
after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - node ./node_modules/.bin/gulp doc:pub
